language: node_js
jobs:
  include:
    - stage: test
      node_js: 8
      script:
        - yarn test
        - yarn build
    - node_js: 10
      script:
        - yarn test
        - yarn build
    - node_js: 12
      script:
        - yarn lint:commit-travis
        - yarn lint
        - yarn test
        - yarn build
      after_success: yarn coveralls
    - stage: release
      if: branch = master AND type = push
      node_js: 12
      script: yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
    - stage: deploy node-mdl-starter
      if: tag =~ ^v AND type = push
      node_js: 12
      env:
        GITHUB_USERNAME: sharvit
        PROJECT_NAME: node-mdl-starter
      install: yarn global add yo generator-node-mdl
      script: ./script/build-node-mdl-starter.sh
      deploy:
        on:
          tags: true
        provider: script
        skip_cleanup: true
        script: ./script/deploy-node-mdl-starter.sh
