'use strict';

const path = require('path');
const Generator = require('yeoman-generator');
const camelCase = require('lodash.camelcase');
const kebabCase = require('lodash.kebabcase');
const chalk = require('chalk');
const commandExists = require('command-exists');
const findUp = require('find-up');
const makeDir = require('make-dir');

module.exports = class extends Generator {
  prompting() {
    return this.prompt([
      {
        name: 'projectName',
        message: 'Project name',
        default: kebabCase(this.appname),
        filter: kebabCase,
      },
      {
        name: 'description',
        message: 'Description',
        default: 'Generated by `generator-node-mdl`',
        store: true,
      },
      {
        name: 'name',
        message: "Author's name",
        default: this.user.git.name(),
      },
      {
        name: 'email',
        message: "Author's email",
        default: this.user.git.email(),
      },
      {
        name: 'website',
        message: "Author's website",
        store: true,
      },
      {
        name: 'githubUsername',
        message: 'GitHub username',
        store: true,
      },
      {
        name: 'githubTemplates',
        message: 'Would you like to make it Github friendly for contributions?',
        type: 'confirm',
        default: true,
      },
      {
        name: 'travisCI',
        message: 'Give your project super prowers using Travis CI?',
        type: 'confirm',
        default: true,
        when: () => {
          this.log(
            '\nLearn how to use Travis CI: https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci'
          );
          return true;
        },
      },
      {
        name: 'coveralls',
        message: 'Connect TravisCI to Coveralls?',
        type: 'confirm',
        default: true,
        when: ({ travisCI }) => {
          if (travisCI) {
            this.log('\nLearn how to use Coveralls: https://coveralls.io');
            return true;
          }

          return false;
        },
      },
      {
        name: 'npmDeploy',
        message: 'Automatically deploy to npm using TravisCI?',
        type: 'confirm',
        default: true,
        when: ({ travisCI }) => {
          if (travisCI) {
            this.log('\nNeed to have an npm account: https://www.npmjs.com/');
            return true;
          }

          return false;
        },
      },
      {
        name: 'npmSecureApiKey',
        message: 'Past your secured api key here:',
        type: 'input',
        when: ({ npmDeploy }) => {
          if (npmDeploy) {
            this.log('\n\n');
            this.log(
              `${chalk.bold('Create a secured-api-key with 3 easy steps:')}`
            );
            this.log('\n');
            this.log(
              '1. Install travis cli: https://github.com/travis-ci/travis.rb#installation'
            );
            this.log('\n');
            this.log(
              '2. Go to your npm dashboard and create a new token: https://www.npmjs.com/settings/<YOUR_USERNAME>/tokens'
            );
            this.log('\n');
            this.log('3. Run `travis encrypt <YOUR_TOKEN>`');
            this.log('\n');
            return true;
          }

          return false;
        },
      },
    ]).then(answers => {
      this.props = {
        projectName: answers.projectName,
        camelProject: camelCase(answers.projectName),
        description: answers.description,
        name: answers.name,
        email: answers.email,
        website: answers.website,
        githubUsername: answers.githubUsername,
        githubTemplates: answers.githubTemplates,
        travisCI: answers.travisCI,
        coveralls: answers.coveralls,
        npmDeploy: answers.npmDeploy,
        npmSecureApiKey: answers.npmSecureApiKey,
      };
    });
  }

  configuring() {
    if (path.basename(this.destinationRoot()) !== this.props.projectName) {
      return makeDir(this.props.projectName).then(path => {
        this.destinationRoot(path);
        this.log(`\nGenerating a new project in ${chalk.green(path)}\n`);
      });
    }
  }

  writing() {
    const templatesToCopy = [
      { templatePath: '_babelrc', destinationPath: '.babelrc' },
      { templatePath: '_editorconfig', destinationPath: '.editorconfig' },
      { templatePath: '_eslintignore', destinationPath: '.eslintignore' },
      { templatePath: '_eslintrc', destinationPath: '.eslintrc' },
      { templatePath: '_gitattributes', destinationPath: '.gitattributes' },
      { templatePath: '_gitignore', destinationPath: '.gitignore' },
      { templatePath: '_package.json', destinationPath: 'package.json' },
      { templatePath: 'license', destinationPath: 'license' },
      { templatePath: 'readme.md', destinationPath: 'readme.md' },
      { templatePath: 'src', destinationPath: 'src' },
    ];

    if (this.props.githubTemplates) {
      templatesToCopy.push(
        { templatePath: '_github', destinationPath: '.github' },
        { templatePath: 'other', destinationPath: 'other' },
        { templatePath: 'contributing.md', destinationPath: 'contributing.md' }
      );
    }

    if (this.props.travisCI) {
      templatesToCopy.push({
        templatePath: '_travis.yml',
        destinationPath: '.travis.yml',
      });
    }

    if (this.props.npmDeploy) {
      templatesToCopy.push({
        templatePath: '_npmignore',
        destinationPath: '.npmignore',
      });
    }

    templatesToCopy.forEach(({ templatePath, destinationPath }) =>
      this.fs.copyTpl(
        this.templatePath(templatePath),
        this.destinationPath(destinationPath),
        this.props
      )
    );
  }

  install() {
    const hasYarn = commandExists.sync('yarn');

    this.installDependencies({
      bower: false,
      npm: !hasYarn,
      yarn: hasYarn,
    });
  }

  end() {
    this.spawnCommandSync('git', ['init', '--quiet']);

    findUp('.yo-rc.json').then(res => {
      if (res) {
        this.fs.delete(res);
      }
    });
  }
};
