module.exports = {
  projectName: {
    type: String,
    required: true,
    desc: 'Project name',
    default: 'Generated by `generator-node-mdl`',
  },
  camelProject: {
    type: String,
    required: true,
    desc: 'Project name camelCase',
  },
  description: {
    type: String,
    required: true,
    desc: 'Project description',
    default: 'Generated by `generator-node-mdl`',
  },
  name: { type: String, required: true, desc: "Author's name" },
  email: { type: String, required: true, desc: "Author's email" },
  website: { type: String, required: true, desc: "Author's website" },
  githubUsername: { type: String, required: true, desc: 'GitHub username' },
  repository: {
    type: String,
    required: true,
    desc: 'Repository name username/project-name',
  },
  githubTemplates: {
    type: Boolean,
    desc: 'Would you like to make it Github friendly for contributions?',
  },
  createGithubRepository: {
    type: Boolean,
    desc: 'Let me create a new github repository for you?',
  },
  coveralls: { type: Boolean, desc: 'Connect TravisCI to Coveralls?' },
  travisCI: {
    type: Boolean,
    desc: 'Give your project super prowers using Travis CI?',
  },
  npmDeploy: {
    type: Boolean,
    desc: 'Automatically deploy to npm using TravisCI?',
  },
  npmToken: {
    type: String,
    desc: 'Your npm-token',
  },
};
