import options from './options';

const prompts = {
  projectName: {
    ...options.projectName,
    required: true,
  },
  description: {
    ...options.description,
    required: true,
    store: true,
    default: 'Generated by `generator-node-mdl`',
  },
  name: {
    ...options.name,
    required: true,
  },
  email: {
    ...options.email,
    required: true,
  },
  website: {
    ...options.website,
    required: true,
    store: true,
    default: 'https://github.com/sharvit/generator-node-mdl',
  },
  githubUsername: {
    ...options.githubUsername,
    required: true,
    store: true,
  },
  githubTemplates: {
    ...options.githubTemplates,
    required: true,
    store: true,
  },
  createGithubRepository: {
    ...options.createGithubRepository,
    required: true,
    store: true,
  },
  travisCI: {
    ...options.travisCI,
    required: true,
    store: true,
    help: () =>
      '\nLearn how to use Travis CI: https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci',
  },
  coveralls: {
    ...options.coveralls,
    required: true,
    store: true,
    dependOn: ['travisCI'],
    help: () => '\nLearn how to use Coveralls: https://coveralls.io',
  },
  npmDeploy: {
    ...options.npmDeploy,
    required: true,
    store: true,
    help: () => '\nNeed to have an npm account: https://www.npmjs.com/',
  },
  semanticRelease: {
    ...options.semanticRelease,
    required: true,
    store: true,
    help: () =>
      '\nLearn more about semantic-release: https://semantic-release.gitbook.io/semantic-release/',
  },
};

export default prompts;
