window.esdocSearchIndex = [
  [
    "generator-node-mdl/src/app/lib/github.js~github",
    "class/src/app/lib/github.js~Github.html",
    "<span>Github</span> <span class=\"search-result-import-path\">generator-node-mdl/src/app/lib/github.js</span>",
    "class"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber4",
    "Commander",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber46",
    "Commander should _runCommand",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber15",
    "Commander should create an instance with no args",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber87",
    "Commander should log command",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber63",
    "Commander should parse a string command",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber72",
    "Commander should parse an array command",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber25",
    "Commander should run commands",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber37",
    "Commander should run one command",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/commander.test.js.html#lineNumber81",
    "Commander should throw error when parse unsupported command type",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/github.test.js.html#lineNumber11",
    "Github",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/github.test.js.html#lineNumber61",
    "Github should authenticate",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/github.test.js.html#lineNumber27",
    "Github should create a new Github instance with basic auth",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/github.test.js.html#lineNumber18",
    "Github should create a new Github instance with token",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/github.test.js.html#lineNumber48",
    "Github should create-repository",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber31",
    "default files",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber80",
    "default files with --noDefaults",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber22",
    "destinationRoot",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/npm.test.js.html#lineNumber4",
    "npm",
    "test"
  ],
  [
    "",
    "test-file/src/app/lib/npm.test.js.html#lineNumber5",
    "npm should login",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber144",
    "prompts",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber418",
    "prompts Travis",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber457",
    "prompts Travis coveralls",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber437",
    "prompts Travis esdoc",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber447",
    "prompts Travis esdoc",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber467",
    "prompts Travis no coveralls",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber513",
    "prompts Travis no npmDeploy",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber428",
    "prompts Travis no travisCI",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber477",
    "prompts Travis npmDeploy",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber524",
    "prompts Travis npmDeploy with semanticRelease",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber556",
    "prompts Travis npmDeploy with semanticRelease and w/o createGithubRepository",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber419",
    "prompts Travis travisCI",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber230",
    "prompts createGithubRepository with token",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber256",
    "prompts createGithubRepository with username and password",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber295",
    "prompts createGithubRepository with username, password and 2fa",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber175",
    "prompts description",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber202",
    "prompts email",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber355",
    "prompts esdoc",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber381",
    "prompts githubTemplates",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber187",
    "prompts name",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber340",
    "prompts no createGithubRepository",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber368",
    "prompts no esdoc",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber402",
    "prompts no githubTemplates",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber145",
    "prompts projectName",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber216",
    "prompts website",
    "test"
  ],
  [
    "",
    "test-file/src/app/index.test.js.html#lineNumber132",
    "remove .yo-rc.json if exists",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/app/generators/base-generator.js",
    "file/src/app/generators/base-generator.js.html",
    "src/app/generators/base-generator.js",
    "file"
  ],
  [
    "src/app/generators/github/index.js",
    "file/src/app/generators/github/index.js.html",
    "src/app/generators/github/index.js",
    "file"
  ],
  [
    "src/app/generators/project/index.js",
    "file/src/app/generators/project/index.js.html",
    "src/app/generators/project/index.js",
    "file"
  ],
  [
    "src/app/generators/travis/index.js",
    "file/src/app/generators/travis/index.js.html",
    "src/app/generators/travis/index.js",
    "file"
  ],
  [
    "src/app/index.js",
    "file/src/app/index.js.html",
    "src/app/index.js",
    "file"
  ],
  [
    "src/app/index.test.js",
    "file/src/app/index.test.js.html",
    "src/app/index.test.js",
    "file"
  ],
  [
    "src/app/index.test.js",
    "test-file/src/app/index.test.js.html",
    "src/app/index.test.js",
    "testFile"
  ],
  [
    "src/app/lib/commander.js",
    "file/src/app/lib/commander.js.html",
    "src/app/lib/commander.js",
    "file"
  ],
  [
    "src/app/lib/commander.test.js",
    "file/src/app/lib/commander.test.js.html",
    "src/app/lib/commander.test.js",
    "file"
  ],
  [
    "src/app/lib/commander.test.js",
    "test-file/src/app/lib/commander.test.js.html",
    "src/app/lib/commander.test.js",
    "testFile"
  ],
  [
    "src/app/lib/github.js",
    "file/src/app/lib/github.js.html",
    "src/app/lib/github.js",
    "file"
  ],
  [
    "src/app/lib/github.js~github#constructor",
    "class/src/app/lib/github.js~Github.html#instance-constructor-constructor",
    "src/app/lib/github.js~Github#constructor",
    "method"
  ],
  [
    "src/app/lib/github.test.js",
    "file/src/app/lib/github.test.js.html",
    "src/app/lib/github.test.js",
    "file"
  ],
  [
    "src/app/lib/github.test.js",
    "test-file/src/app/lib/github.test.js.html",
    "src/app/lib/github.test.js",
    "testFile"
  ],
  [
    "src/app/lib/npm.js",
    "file/src/app/lib/npm.js.html",
    "src/app/lib/npm.js",
    "file"
  ],
  [
    "src/app/lib/npm.test.js",
    "file/src/app/lib/npm.test.js.html",
    "src/app/lib/npm.test.js",
    "file"
  ],
  [
    "src/app/lib/npm.test.js",
    "test-file/src/app/lib/npm.test.js.html",
    "src/app/lib/npm.test.js",
    "testFile"
  ],
  [
    "src/app/options.js",
    "file/src/app/options.js.html",
    "src/app/options.js",
    "file"
  ],
  [
    "src/app/prompter.js",
    "file/src/app/prompter.js.html",
    "src/app/prompter.js",
    "file"
  ],
  [
    "src/app/prompts.js",
    "file/src/app/prompts.js.html",
    "src/app/prompts.js",
    "file"
  ]
]