#!/bin/bash

set -e

GITHUB_USERNAME=$GITHUB_USERNAME
GITHUB_NAME=$GITHUB_NAME
GITHUB_EMAIL=$GITHUB_EMAIL
GITHUB_WEBSITE=$GITHUB_NAME
PROJECT_NAME=$PROJECT_NAME
STARTER_GH_TOKEN=$STARTER_GH_TOKEN
STARTER_NPM_TOKEN=$STARTER_NPM_TOKEN
GENERATOR_NODE_MDL_VERSION=$TRAVIS_TAG

echo "Building ${PROJECT_NAME} using generator-node-mdl ${GENERATOR_NODE_MDL_VERSION}"

git clone https://${STARTER_GH_TOKEN}@github.com/${GITHUB_USERNAME}/${PROJECT_NAME}.git
cd $PROJECT_NAME

yo node-mdl \
  --npmToken $STARTER_NPM_TOKEN \
  --githubToken $STARTER_GH_TOKEN \
  --projectName $PROJECT_NAME \
  --description "Generated by generator-node-mdl" \
  --name $GITHUB_NAME \
  --email $GITHUB_EMAIL \
  --website $GITHUB_WEBSITE \
  --githubUsername $GITHUB_USERNAME \
  --noDefaults \
  --githubTemplates \
  --esdoc \
  --coveralls \
  --travisCI \
  --npmDeploy \
  --semanticRelease \
  --force
