#!/bin/bash

set -e

GITHUB_USERNAME=$GITHUB_USERNAME
PROJECT_NAME=$PROJECT_NAME
STARTER_GH_TOKEN=$STARTER_GH_TOKEN
STARTER_NPM_TOKEN=$STARTER_NPM_TOKEN
GENERATOR_NODE_MDL_VERSION=$TRAVIS_TAG

echo "Building node-mdl-starter with generator-node-mdl ${GENERATOR_NODE_MDL_VERSION}"

git clone https://${STARTER_GH_TOKEN}@github.com/${GITHUB_USERNAME}/${PROJECT_NAME}.git
cd $PROJECT_NAME

yo node-mdl \
  --npmToken $STARTER_NPM_TOKEN \
  --githubToken $STARTER_GH_TOKEN \
  --projectName $PROJECT_NAME \
  --description "Generated by generator-node-mdl" \
  --name "Avi Sharvit" \
  --email "sharvita@gmail.com" \
  --website "https://sharvit.github.io" \
  --githubUsername $GITHUB_USERNAME \
  --noDefaults \
  --githubTemplates \
  --coveralls \
  --travisCI \
  --npmDeploy \
  --semanticRelease \
  --force
