language: node_js
jobs:
  include:
    - stage: test
      node_js: 10
      script:
        - yarn test
        - yarn build
    - node_js: 12
      script:<% if (semanticRelease) { %>
        - yarn lint:commit-travis<% } %>
        - yarn lint
        - yarn test
        - yarn build<% if (coveralls) { %>
      after_success: yarn coveralls<% } if (npmDeploy) { %>
    - stage: release
      if: branch = master AND type = push
      node_js: 12
      script: yarn build
      deploy:<% if (semanticRelease) { %>
        - provider: script
          skip_cleanup: true
          script: yarn semantic-release<% } else { %>
        - provider: npm
          skip_cleanup: true
          email: <%= email %>
          api_key: $NPM_TOKEN
          on:
            node: 10
            tags: true
            repo: <%= githubUsername %>/<%= projectName %>
      <% } if (esdoc) { %>
        - provider: pages
          skip_cleanup: true
          github_token: $GH_TOKEN
          local_dir: ./docs
          keep_history: true
      <% } %>
    <% } %>
