name: generator-node-mdl ci

on: ["push", "pull_request"]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      GITHUB_NAME: "Avi Sharvit"
      GITHUB_EMAIL: sharvita@gmail.com
    steps:
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Configure git
        run: |
          git config --global user.email "${GITHUB_EMAIL}"
          git config --global user.name "${GITHUB_NAME}"
      - name: Checkout generator-node-mdl
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v1
        with:
          configFile: .commitlintrc.json
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
